- hosts: [mesos_masters]
  sudo: True
  roles:
    - { role: ansible-docker, tags:['os-tools'] }
    - { role: ansible-java8, tags:['runtimes', 'java']}
#    - { role: ansible-scala, scala_version: "2.10.4", tags:['runtimes'] }
#    - { role: ansible-sbt, sbt_version: "0.13.1", tags:['scala-tools'] }
    - { role: ansible-mesos, mesos_version: "0.19.0", tags: ['mesos', 'platforms'] }
    - { role: ansible-marathon, tags:['mesos-tools'] }
    - { role: ansible-mesos-docker, mesos_docker_branch: "master", tags:['mesos-tools'] }
- hosts: [mesos_slaves]
  sudo: True
  roles: 
    - { role: ansible-docker, tags:['os-tools'] }
    - { role: ansible-java8, tags:['runtimes', 'java']}
    - { role: ansible-mesos, mesos_install_mode: "slave", mesos_version: "0.19.0", tags: ['mesos', 'platforms'] }
    - { role: ansible-mesos-docker, mesos_docker_branch: "master", tags:['mesos-tools'] }

#- include: tests/integration-tests.yml tags=mesos

  #http://downloads.mesosphere.io/master/ubuntu/12.04/mesos_0.19.0~ubuntu12.04%2B1_amd64.deb
