- hosts: [mesos_masters]
  sudo: True
  pre_tasks: 
    - name: Install Debian Packages
      apt: pkg={{ item }} state=present
      with_items:
        - git
        - vim
        - htop
        - haproxy
      when: ansible_os_family == "Debian"
    - name: Downloading and enable the EPEL repository definitions.
      action: command rpm -Uvh --replacepkgs http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
      when: ansible_os_family == "RedHat"
    - name: Install Redhat Packages 
      yum: pkg={{ item }} state=present
      with_items:
        - java7
        - git
        - vim
        - htop
        - haproxy
      when: ansible_os_family == "RedHat"
    - name: Disable iptables
      action: service name=iptables state=stopped enabled=false
#    - name: Sets haproxy to enabled
#      lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"

  roles:
    - { role: './librarian_roles/ansible-java8', tags:['runtimes', 'java'], when: ansible_os_family == 'Debian' }
    - { role: './librarian_roles/ansible-zookeeper', zookeeper_hosts: "{{ groups.mesos_masters}}", tags:['zookeeper'] }
    - { role: './librarian_roles/ansible-mesos', zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}", mesos_install_mode: 'master', mesos_cluster_name: 'mlh_mesos', tags: ['mesos', 'platforms'] }
    - { role: './librarian_roles/ansible-marathon', zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}",  tags:['mesos-tools'] }

- hosts: [mesos_slaves]
  sudo: True
  roles: 
    - { role: './librarian_roles/ansible-java8', tags:['runtimes', 'java'], when: ansible_os_family == 'Debian' }
    - { role: './librarian_roles/ansible-mesos', zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}",  mesos_install_mode: "slave", tags: ['mesos', 'platforms'] }
