---
- debug: msg="Install Mode is {{mesos_install_mode}}"

- name: Download mesos v{{mesos_version}}
  get_url: url={{mesos_download_url}} dest={{mesos_dest_file}}

- name: Download mesos v{{mesos_version}} python bindings (egg file)
  get_url: url={{mesos_python_download_url}} dest={{mesos_python_dest_file}}
