---
- name: Download Marathon version {{ marathon_version }}
  get_url: url={{marathon_url}} dest={{marathon_dest_file}}

- name: Extract Archive
  command: tar -xzf {{ marathon_dest_file }} --strip 1 -C {{ marathon_install_location }}
  notify: 
    - restart marathon

- name: Setup haproxy script
  copy: src=haproxy_dns_cfg dest="{{ marathon_install_location }}/bin/haproxy_dns_cfg" mode=755

- name: Init haproxy
  command: "{{ marathon_install_location }}/bin/haproxy_reload"

- name: Setup Cron Job
  cron: name="reload marathon haproxy" minute="*/1" job="{{ marathon_install_location }}/bin/haproxy_reload"
